/* Template source file generation only partially implemented. */
/* ----------------------------------------------------------------------- */
/* Template source file generated by piklab */
#include "config.h"

#define USE_AND_OR
#include <libpic30.h>
#include "display.h"
#include "font.h"
#include "sensors.h"
#include "interface.h"
#include "peripherals.h"
#include "battery.h"



void main(){
    //various init functions
	peripherals_init();
	peripherals_on(true);
	i2c_init();
	config_init();
	display_init();
	sensors_init();
	interface_init();
	display_clear_screen();
	
	while(true) show_menu(FIRST_MENU_ITEM,true);
}
